---
language: node_js
node_js:
  - "4"

sudo: false
dist: trusty

addons:
  firefox: "44.0"

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-2.0.X
  - EMBER_TRY_SCENARIO=ember-2.1.X
  - EMBER_TRY_SCENARIO=ember-2.2.X
  - EMBER_TRY_SCENARIO=ember-2.3.X
  - EMBER_TRY_SCENARIO=ember-2.4.X
  - EMBER_TRY_SCENARIO=ember-2.5.X
  - EMBER_TRY_SCENARIO=ember-2.6.X
  - EMBER_TRY_SCENARIO=ember-2.7.X
  - EMBER_TRY_SCENARIO=ember-beta


before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - npm config set spin false
  - npm install -g npm@^2
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5

script:
  - ember try:one $EMBER_TRY_SCENARIO --- ember test --launch=firefox --reporter=dot
